### ISSUE TITLE
Increase Test Coverage

### ISSUE THREAD

**Issue by TopsonArcana** [GarnBarn/garnbarn-frontend#10]
## Is your feature request related to a problem? Please describe.
The coverage for our project is quite low at the moment.
[![codecov](https://codecov.io/gh/GarnBarn/garnbarn-frontend/branch/master/graph/badge.svg?token=QwED3bFABW)](https://codecov.io/gh/GarnBarn/garnbarn-frontend)

## Describe the solution you'd like
We should write more tests to increase our coverage.

**Comment by sirateek** [comment]
This has been implemented in #11. Closing this (for now).
