### ISSUE TITLE
[BUG]: Tag color not change in the first time when edit color

### ISSUE THREAD

**Issue by nabhan-au** [GarnBarn/garnbarn-frontend#46]
## Describe the bug

When clicking change tag color in the assignment. Color won't change in the first time. But it change in the second time that I edit.

## Step To Reproduce the bug:

1. Go to home page and login
2. Click on the assignment
3. Click on edit button
4. Change color
5. Tag not change color (Bug here)
6. Click on edit button again
7. Change color
8. Tag change their  color

## Expected behavior

The color tag should change in the first time that I edit

## Screenshots

![Screenshot 2021-11-24 205006](https://user-images.githubusercontent.com/70481664/143254938-54fdb053-9048-4c68-9c85-db2a7ded97b7.jpg)

## Hardware Spec (please complete the following information):

- Device: Computer
- OS: window10
- Browser: Google Chrome
- Version: 96.0.4664.45 (Official Build) (64-bit)

**Comment by sirateek** [comment]
Thank you for reporting this to me. I can definitely reproduce the bug now. It seems that it is the problem with our color picker tools. This will be fixed soon.

**Comment by sirateek** [comment]
This has been fixed in #49 and has been deployed to the production environment. Thank you again for reporting this to us.
