### ISSUE TITLE
Create Assignment component

### ISSUE THREAD

**Issue by TopsonArcana** [GarnBarn/garnbarn-frontend#6]
Make an assignment component to be used on the Assignment detail page.

**Comment by sirateek** [comment]
@TopsonArcana, Please update the status of this ticket.

**Comment by TopsonArcana** [comment]
Currently, the component is partly done, it has the detail on it as a prop. It's missing the edit button with the form to edit (maybe this one is for another component) and a test for the component.

**Comment by TopsonArcana** [comment]
This is already done in  PR #12, closing this issue.
